In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
arr2 = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

In [3]:
# (+) add operation to add two array
print(arr + arr2)
# .add() function to add two array
print(np.add(arr,arr2))

[[ 20  40  60  80]
 [ 60  80 100 120]
 [100 120 140 160]]
[[ 20  40  60  80]
 [ 60  80 100 120]
 [100 120 140 160]]


In [4]:
# (-) subtract operation to subtract two array
print(arr - arr2)
# .subtract() function to subtract two array
print(np.subtract(arr,arr2))

[[  0   0   0   0]
 [-40 -40 -40 -40]
 [-80 -80 -80 -80]]
[[  0   0   0   0]
 [-40 -40 -40 -40]
 [-80 -80 -80 -80]]


In [5]:
# (*) multiply operation to multiply two array
print(arr * arr2)
# .multiply() function to multiply two array
print(np.multiply(arr,arr2))

[[ 100  400  900 1600]
 [ 500 1200 2100 3200]
 [ 900 2000 3300 4800]]
[[ 100  400  900 1600]
 [ 500 1200 2100 3200]
 [ 900 2000 3300 4800]]


In [6]:
# (/) divide operation to divide two array
print(arr / arr2)
# .divide() function to divide two array
print(np.divide(arr,arr2))

[[1.         1.         1.         1.        ]
 [0.2        0.33333333 0.42857143 0.5       ]
 [0.11111111 0.2        0.27272727 0.33333333]]
[[1.         1.         1.         1.        ]
 [0.2        0.33333333 0.42857143 0.5       ]
 [0.11111111 0.2        0.27272727 0.33333333]]


In [7]:
# (**) power operation to find power of two array
print(arr ** arr2)
# .power() function to find power of two array
print(np.power(arr,arr2))

[[         10000000000 -2101438300051996672  2565992168703393792
                     0]
 [-5376172055173529600                    0                    0
                     0]
 [                   0                    0                    0
                     0]]
[[         10000000000 -2101438300051996672  2565992168703393792
                     0]
 [-5376172055173529600                    0                    0
                     0]
 [                   0                    0                    0
                     0]]


In [8]:
# .sqrt() function to find square root of array element
print(np.sqrt(arr))

[3.16227766 4.47213595 5.47722558 6.32455532]
